### PR TITLE
Added code to support file templateing.

### PR DESCRIPTION
**Pull request by Samurai336**
You can now add template tokens to you json.

### CODE REVIEW

**Comment by gstroup** [comment]
This looks like it could be useful.  I have seen a real API that sends back request parameters in the response.  My only concern is that this is doing multiple string.replace() calls on every response.   I'll take a look and try to get it merged and published soon.  Thank you for the PR!

**Comment by Samurai336** [comment]
Hi gstroup:

Other then looping though for each token how would you go about doing it? 

Also, you comment made me realize I was only updating the first instance of the token, so I've updated the code to replace all instances.

**Comment by Samurai336** [comment]
Hi gstroup:

Any updates?

**Comment by gstroup** [comment]
Hi, I'm fine with looping through for each token.  I was thinking about people that don't want to use templates... This code will still loop through for each param.  Can we add an option, then check: if (options.fillTemplate) { call fillTemplate function }

What do you think?

Overall, looks good!  Thank you.

**Comment by Samurai336** [comment]
Hi gstroup:

That makes sense! I've gone ahead and done that. Let me know if you agree with my naming and implementation.

**Comment by gstroup** [comment]
Looks good.  Thanks!!  I'll get it merged and published as soon as I can.
   -Greg

**Comment by Samurai336** [comment]
Any news on merging this?

**Comment by gstroup** [comment]
Sorry for the delay.  It's merged now, and published as version 0.4.11.  Thank you!

**Comment by Samurai336** [comment]
Awesome! Thank you.

**Pull request merged**
