### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by kopach**
- Update npm dependencies
   https://npms.io/search?q=apimocker shows package as insecure because of security vulnerabilities which present in old packages
- add package-lock.json
- update deprecated `sendfile()` method of express
- fix url encoding problem - fixes issue #20

### CODE REVIEW

**Comment by kopach** [comment]
looks like CI fails on old node version only. if you really need to support such an old version - downgrade `express-http-proxy` back

**Comment by gstroup** [comment]
Thanks for updating the dependencies!  This is great.  Only issue is the node version... I don't care about 0.10 any more, but I don't want to force people to use 9 quite yet. Can we do >=4 or 5?

**Comment by kopach** [comment]
@gstroup, but check CI details. tests fail only for node `v0.10`. It works fine on >=4 or 5
Anyway, if you need `v0.10` - it's still possible to accomplish, but personally I don't see any sense in that :)

**Comment by gstroup** [comment]
Thanks!  publishing a new version to npm now.

**Pull request merged**
