### PR TITLE
Rebase from Master

### PR DESCRIPTION
**Pull request by ricardo-hdz**

### CODE REVIEW

**Comment by ricardo-hdz** [comment]
@gstroup Please update Travis to use the rebased version. Or accept this PR to merge the rebase.

**Comment by gstroup** [comment]
What's the purpose of this PR?  The "travis" branch is old, and not used for anything.  I set it up when I was first playing with Travis.  I should probably delete it now.  The master branch is where the tests are running now.  Is there another reason for this PR?  Thanks for your contributions!

**Comment by ricardo-hdz** [comment]
@gstroup I will close this then. I though Travis used this branch to run the CI.

**Comment by gstroup** [comment]
Sorry for the confusion.  I will delete that branch.  Thanks!

**Pull request closed without merging**
