### PR TITLE
Add support for flexible 'templateSwitch' request/response substitution

### PR DESCRIPTION
**Pull request by ferrerod**
borrowing heavily from the 'switch' code, and the template concept I've enhanced this to support GET and POST support including POST BODY parameter matching with JSONPath.

### CODE REVIEW

**Comment by gstroup** [comment]
Thanks for the PR.  Looks like a pretty big addition.  I'll take a look.  Also, please ensure that all the tests are passing, and add a few tests for your new feature.  Thanks!

**Comment by ferrerod** [comment]
fixed tests and synced with master

**Comment by ferrerod** [comment]
Hi gstroup:
let me know if you would like more information on my PR. Adds support for templating including POST body content.

**Comment by gstroup** [comment]
Sorry, I haven't had much time to maintain this project lately.  Your PR looks good.  Only thing is that there are no tests.  Could you possibly add a few basic tests??  Then I will merge it in.  Let me know if you have questions.  Thanks again!

**Comment by ferrerod** [comment]
👍 tests added. Let me know if this looks adequate. Thanks.

**Comment by gstroup** [comment]
Great!  Thanks for adding some tests.  This makes me feel better.  And you fixed a bug too!  👍 
I will merge and push a new version to npm.

**Pull request merged**
